In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
data ={
"area":[2600,3000,3200,3600,4000],
"price":[550000,565000,610000,680000,725000]
}
df=pd.DataFrame(data)

In [7]:
print(df)

   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000


In [8]:
reg=linear_model.LinearRegression()

reg.fit(df[['area']],df.price)

LinearRegression()

In [9]:
x=5000

In [10]:
reg.predict(np.array([[x]]))

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [11]:
m=reg.coef_

In [12]:
import pickle

In [13]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [14]:
with open('model_pickle','rb') as f:
    model = pickle.load(f)

In [15]:
model.predict(np.array([[5000]]))

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [17]:
import joblib

In [18]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [19]:
mj=joblib.load('model_joblib')

In [21]:
mj.predict(np.array([[5000]]))

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [22]:
mj.coef_

array([135.78767123])

In [23]:
mj.intercept_

180616.43835616432